name: formwork_example
description: Example app for formwork.
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^3.3.2
  formwork:
    path: ../
  formwork_material:
    path: ../../formwork_material
  shadcn_ui: ^0.53.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
